config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "external#landing"

  scope module: :external do
    get :landing
    get :about
    get :contact
    get :facility
    get :personnel
    get :research
    get :services
    get :sitemap_xml, path: "sitemap.xml.gz"
    get :thanks
    get :privacy_policy, path: "privacy-policy"
    get :version
    post :submit_contact, path: "contact"
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# Base class for application models.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Main web application controller for Boston Sleep website.
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :devise_login?
  before_action :configure_permitted_parameters, if: :devise_controller?

  layout "full_page_no_header"

  protected

  def devise_login?
    params[:controller] == "devise/sessions" && params[:action] == "create"
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: [:first_name, :last_name, :email, :password, :password_confirmation, :emails_enabled]
    )
  end
end

app/controllers/external_controller.rb
# frozen_string_literal: true

# Displays publicly available pages.
class ExternalController < ApplicationController
  layout "layouts/full_page_no_header"

  # # GET /about
  # def about
  # end

  # # GET /contact
  # def contact
  # end

  # # GET /
  # def landing
  # end

  # # GET /facility
  # def facility
  # end

  # # GET /research
  # def research
  # end

  # # GET /services
  # def services
  # end

  # GET /sitemap.xml.gz
  def sitemap_xml
    sitemap_xml = File.join(CarrierWave::Uploader::Base.root, "sitemaps", "sitemap.xml.gz")
    if File.exist?(sitemap_xml)
      send_file sitemap_xml
    else
      head :ok
    end
  end

  # # GET /personnel
  # def personnel
  # end

  # # GET /thanks
  # def thanks
  # end

  # # GET /privacy-policy
  # def privacy_policy
  # end

  # # GET /version
  # # GET /version.json
  # def version
  # end

  # POST /submit_contact
  def submit_contact
    if params[:name].present? && params[:email].present? && params[:comments].present?
      send_contact_email
      redirect_to thanks_path
    else
      render :contact
    end
  end

  private

  def send_contact_email
    UserMailer.contact(params[:name], params[:email], params[:comments]).deliver_now if EMAILS_ENABLED
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Provides methods that can be used across all views.
module ApplicationHelper
  def apply_markdown(text, table_class: "", allow_lists: true)
    markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML,
      no_intra_emphasis: true, fenced_code_blocks: true, autolink: true,
      strikethrough: true, superscript: true, tables: true, lax_spacing: true,
      space_after_headers: true, underline: true, highlight: true, footnotes: true
    )
    result = text.to_s
    result = replace_numbers_with_ascii(result) unless allow_lists
    result = markdown.render(result)
    result = result.encode("UTF-16", undef: :replace, invalid: :replace, replace: "").encode("UTF-8")
    result = add_table_class(result, table_class) unless table_class.blank?
    result.html_safe
  end

  def add_table_class(text, table_class)
    text.to_s.gsub(/<table>/m, "<table class=\"#{table_class}\">").html_safe
  end

  def src_abbr
    content_tag :abbr, "SRC", title: "Sleep Reading Center"
  end
end

app/views/external/about.html.haml
- @title = "About"

.page-box.last-box.page-box-no-padding.background-p50-grey
  = render "layouts/small_heading"

  .page-box-padding
    .container
      .row
        .col-sm-2.d-none.d-sm-block
          = render "menu/left_menu"
        .col-sm-10
          .backdrop-white
            %p.lead
              The primary mission of the
              Sleep Reading Center
              = surround "(", ")" do
                = src_abbr
              is to partner with research teams to
              ensure that the highest quality sleep data are collected, analyzed
              and reported in order to advance the understanding of sleep and
              health.
          .backdrop-regular
            Since 1994, the
            = src_abbr
            has led all aspects of
            sleep data acquisition and processing for numerous large-scale
            observational studies and clinical trials for both adult and pediatric
            study populations. The
            = src_abbr
            was the first major research PSG center
            supporting large studies funded by the National Institutes of Health.
            During the last 23 years, our team has developed rigorous approaches
            for obtaining, processing, and scoring of polysomnograms in
            multi-center studies; implemented methods for training, certification,
            and quality improvement to achieve highly standardized, accurate, and
            reliable data collection across multiple sites; and assisted with the
            development of sophisticated informatics platforms to support
            multi-site clinical research. As our portfolio of services has
            expanded, we have successfully applied these approaches to our other
            service offerings.
          .backdrop-regular
            %p
              = link_to services_path do
                Our services
                = icon("fas", "caret-right")

app/views/external/contact.html.haml
- @title = "Contact"

.page-box.last-box.page-box-no-padding.background-p50-grey
  = render "layouts/small_heading"

  .page-box-padding
    .container
      .row
        .col-sm-2.d-none.d-sm-block
          = render "menu/left_menu"
        .col-sm-10
          .backdrop-regular
            %p
              %strong For all inquiries regarding new projects

            %p
              Dr. Susan Redline, MD, MPH, Director
              %br
              %small Brigham Health Sleep Reading Center
              %br
              %small Brigham and Women's Hospital
              %br
              %small Harvard Medical School
              %br
              %small 221 Longwood Avenue, Boston, MA 02115
              %br
              %small
                Email:
                = mail_to "sredline@bwh.harvard.edu"

          .backdrop-regular
            %p
              %strong
                For general inquiries regarding
                = src_abbr
                services
            %p
              Dan Mobley
              %br
              %small Brigham Health Sleep Reading Center
              %br
              %small Brigham and Women's Hospital
              %br
              %small 221 Longwood Avenue, Boston, MA 02115
              %br
              %small
                Phone:
                = link_to "857.307.0338", "tel:857.307.0338"
              %br
              %small
                E-mail:
                = mail_to "dmobley@bwh.harvard.edu"

          .backdrop-white
            %p
              %strong Leave us a message.

            = form_with url: submit_contact_path, method: :post, local: true do |form|
              .row
                .col-sm-6.form-group
                  = form.text_field :name, value: params[:name], class: "form-control", placeholder: "Name", autocomplete: "off"
                .col-sm-6.form-group
                  = form.email_field :email, value: params[:email], class: "form-control", placeholder: "Email", autocomplete: "off"
              .form-group
                = form.text_area :comments, value: params[:comments], class: "form-control", placeholder: "Comment", rows: 5
              .form-group.row.mt-4.mb-0
                .col-sm-12
                  = form.submit "Send", class: "btn btn-primary float-right"

app/views/external/facility.html.haml
- @title = "Facility"

.page-box.last-box.page-box-no-padding.background-p50-grey
  = render "layouts/small_heading"

  .page-box-padding
    .container
      .row
        .col-sm-2.d-none.d-sm-block
          = render "menu/left_menu"
        .col-sm-10
          .backdrop-white
            %p.lead
              The
              = src_abbr
              is located within the Division of Sleep and Circadian Disorders at
              the Brigham and Women's Hospital, a primary teaching hospital of the
              adjacent Harvard Medical School.

          .backdrop-regular
            %p
              All research activities, including technical work and project
              management, take place in the centrally located
              = src_abbr
              research facility that is designed to enhance the cohesion and
              communication among project team members as well as promote smooth
              and efficient operations. Data analyses are performed by highly
              trained personnel using a variety of statistical software packages
              including SAS and R.

          .backdrop-regular
            %p
              %strong Big Data Capabilities
            %p
              The
              = src_abbr
              maintains dedicated workstations for analysis of sleep data. The
              systems are fully secured, and facilitate access to highly reliable
              file storage and secure file transmission systems for receipt and
              transmission of de-identified data. Partners Information Services
              (IS), a division within Partner Healthcare Systems (PHS), manages
              all data and voice communication networks as well as other core
              infrastructure systems and applications across the Partners
              environment with a budget of over $300M per annum. The PHS data
              network provides 100 MB Ethernet connections to the desktop with 1
              GB access layer connections to the core. When required, higher
              bandwidth connections are available to the desktop. The network core
              consists of redundant connections among 4 major datacenters located
              in MGH Boston, Charlestown, BWH Longwood Medical Area, and Needham,
              MA. Redundancy is maintained from all areas of the network to the
              institution's Internet Service Provider.

          .backdrop-regular
            %p
              %strong Data Security
            %p
              All computer workstations are maintained and supported by Brigham
              and Women's Hospital and Partners Corporation Information Systems.
              All workstations have institutional level virus protection software,
              are locked when not in use, and require a staff-specific user name
              and password for logon. The
              = src_abbr
              maintains strict policies regarding safeguarding and adheres to
              industry best practices for password management and user access
              auditing. All work related to a specific project is saved within
              secure network spaces accessible only to team members authorized to
              work on the study. This network is accessible only by
              = src_abbr
              staff members who are granted permission by the
              = src_abbr
              Administrative Director. Institution-wide backup of all server data
              is performed nightly, and
              = src_abbr
              project-specific data are additionally stored on secured servers
              with remote redundant back-up protection. The Partners Corporation
              operates under a full compendium of policies related to Emergency
              Management and Disaster Recovery policies that address data recovery
              and upstart after any unexpected and unforeseen catastrophe. PHS has
              necessary physical and operational securities in place for all
              operational controls to meet or exceed Federal and State security
              and privacy regulations. PHS restricts, monitors, and controls
              access to systems by authorized staff who additionally have signed
              confidentiality and ethical pledges to safeguard data.

          .backdrop-regular
            %p
              %strong Fully Supported by Partners Infrastructure
            %p
              Partners Information Services (IS) manages all data and voice
              communication networks as well as other core infrastructure systems
              and applications across the Partners environment. Cloud-based,
              virtual services are available to researchers and are maintained
              using enterprise-class IT systems within the Partners secure data
              center and within the Partners network.

          .backdrop-regular
            %p
              = link_to research_path do
                Our research
                = icon("fas", "caret-right")

app/views/external/landing.html.haml
.page-box.last-box.page-box-no-padding.background-p50-grey
  = render "layouts/heading"

  .page-box-padding.background-p50-grey
    .container
      .row
        .col-sm-2.d-none.d-sm-block
          = render "menu/left_menu"
        .col-sm-10
          .backdrop-white
            %p.lead
              The Brigham Health Sleep Reading Center
              = surround "(", ")" do
                = src_abbr
              provides a full suite of services needed for obtaining high quality
              sleep data for large scale clinical trials and cohort studies.
              Established by Susan Redline, MD, MPH in 1994, the
              = src_abbr
              has analyzed more than 50,000 studies and is the premiere provider
              of a full suite of services that can be tailored to meet the needs
              of each study.
          .backdrop-regular
            %p
              = link_to about_path do
                Learn more
                = icon("fas", "caret-right")

app/views/external/personnel.html.haml
- @title = "Personnel"

.page-box.last-box.page-box-no-padding.background-p50-grey
  = render "layouts/small_heading"

  .page-box-padding
    .container
      .row
        .col-sm-2.d-none.d-sm-block
          = render "menu/left_menu"
        .col-sm-10
          .backdrop-white
            %p
              %strong
                Leadership
            %p
              = succeed "," do
                = link_to "Dr. Susan Redline", "https://connects.catalyst.harvard.edu/Profiles/display/Person/27634"
              MD, MPH, Director
              %br
              %small Peter C. Farrell Professor of Sleep Medicine, Harvard Medical School
              %br
              %small Senior Physician, Division of Sleep and Circadian Disorders, Departments of Medicine and Neurology, Brigham and Women's Hospital
              %br
              %small Physician, Division of Pulmonary Medicine, Department of Medicine, Beth Israel Deaconess Medical Center

          .backdrop-regular
            %p
              = succeed "," do
                = link_to "Dr. Daniel Gottlieb", "https://connects.catalyst.harvard.edu/Profiles/display/Person/89478"
              MD, MPH, Associate Director (Polysomnography)
              %br
              %small Associate Professor of Medicine, Harvard Medical School
              %br
              %small Associate Physician, Division of Sleep and Circadian Disorders, Departments of Medicine and Neurology, Brigham and Women's Hospital
              %br
              %small Director, Sleep Disorders Center, VA Boston Healthcare System

            %p
              = succeed "," do
                = link_to "Dr. Shaun M. Purcell", "http://zzz.bwh.harvard.edu/about.html"
              PhD, Co-Director, National Sleep Research Resource
              %br
              %small Purcell Lab in Sleep, Psychiatry, and Genetics, Department of Psychiatry, Brigham and Women's Hospital
              %br
              %small Associate Professor of Psychiatry and Genetics and Genomic Sciences, Icahn School of Medicine at Mount Sinai


          .backdrop-regular
            %p
              %strong
                Chief Polysomnologist / Senior Project Manager
            %p Dan Mobley, RPSGT, CCSH

          .backdrop-regular
            %p
              = link_to contact_path do
                Contact us
                = icon("fas", "caret-right")

app/views/external/research.html.haml
- @title = "Research"

.page-box.last-box.page-box-no-padding.background-p50-grey
  = render "layouts/small_heading"

  .page-box-padding
    .container
      .row
        .col-sm-2.d-none.d-sm-block
          = render "menu/left_menu"
        .col-sm-10
          .backdrop-white
            %p.lead
              As part of the Brigham and Women's Hospital Division of Sleep and
              Circadian Disorders, the
              Sleep Reading Center
              = surround "(", ")" do
                = src_abbr
              serves as a vibrant and productive
              research center for investigations related to sleep disorders and
              outcomes in large clinical studies.

          .backdrop-regular
            %p
              The
              = src_abbr
              has worked on numerous analytic studies with a wide variety
              of sponsors, including the National Institutes of Health and
              industry. The
              = src_abbr
              ensures internal quality control and compliance
              with industry regulations for all studies. The
              = src_abbr
              team also works
              closely with sponsors to ensure timely deliverables for each
              project. A selected list of prior and ongoing investigations is
              shown below.

          .backdrop-regular
            %p
              %strong
                = src_abbr
                Publications
              %small
                See a full list of publications on
                - pubmed_url = "https://www.ncbi.nlm.nih.gov/pubmed/?term=redline+susan"
                = link_to "PubMed", pubmed_url
                = succeed "." do
                  = link_to icon("fas", "external-link-alt"), pubmed_url
            %p
              The
              = src_abbr
              research group is comprised of faculty physicians, research
              fellows, polysomnography technicians, and project management staff.
              Each year, research fellows and faculty present their work at
              national and international scientific meetings and publish in
              high-impact sleep and medical journals. All members of the
              = src_abbr
              group benefit from the rich array of education, research, and
              training resources available at the Brigham and Women's Hospital,
              the Harvard Medical School, and campus-wide Harvard affiliated
              institutions. Since Dr. Redline started the first sleep reading
              center, the
              = src_abbr
              research group has contributed to the publication
              of over 200 original articles.

            %p
              To learn more about research and training opportunities at the
              = succeed "," do
                = src_abbr
              please email
              = succeed "." do
                = link_to "Dr. Susan Redline", contact_path
            %p
              Select
              = src_abbr
              Publications include:

          .backdrop-regular
            %p
              %strong
                PSG

            %p Quan S, Howard B, Iber C, Kiley J, Nieto J, O Connor GT, Rapoport DM, Redline S, Robbins J, Samet J, Wahl P. The Sleep Heart Health Study: Design, rationale, and methods. Sleep 1997; 20(12):1077-1085. PMID: 9493915.
            %p Whitney CW, Gottlieb DJ, Redline S, Nieto J, Norman RG, Dodge RR, Shahar E, Surovec S. Reliability of scoring respiratory disturbance indices and sleep staging.  Sleep NIH 50th Year Commemorative Issue. 1998; 21(7):749-757. PMID: 11286351.
            %p Redline S, Sanders M, Lind B, Quan S, Iber C, Gottlieb D, Bonekat W, Rapoport DW, Smith PL, Kiley J. Methods for obtaining and analyzing unattended polysomnography data for a multicenter study. Sleep NIH 50th Year Commemorative Issue. 1998; 21(7):759-767. PMID: 11300121.
            %p Quan SF, Griswold ME, Iber C, Nieto FJ, Rapoport DM, Redline S, Sanders M, Young T. Short-term variability of respiration and sleep during unattended non-laboratory polysomnography—the Sleep Heart Health Study. Sleep. 2002; 25(8):843-849. PMID: 12489889.
            %p Lind BK, Goodwin JL, Hill JG, Tauqeer A, Redline S, Quan SF. Recruitment of healthy adults into a study of overnight sleep monitoring in the home: experience of the Sleep Heart Health Study. Sleep Breath. 2003; 7(1):13-24. PMID: 12712393.
            %p Redline S, Kirchner HL, Quan SF, Gottlieb DJ, Kapur V, Newman A. The effects of age, sex, ethnicity and sleep disordered breathing on sleep architecture. Arch Intern Med. 2004; 164(4):406-418. PMID: 14980992.
            %p Redline S, Budhiraja R, Kapur V, Marcus CL, Mateika JH, Mehra R, Parthasarthy S, Somers VK, Strohl KP, Sulity LG, Gozal D, Wise MD, Quan SF. The scoring of respiratory events in sleep: reliability and validity. J Clin Sleep Med. 2007; 3(2):169-200. PMID: 17557426.
            %p Gottlieb DJ, Yenokyan G, Newman A, O'Connor GT, Punjabi NM, Quan SQ, Redline S, Resnick HE, Tong E, Diener-West M, Shahar E. Prospective study of obstructive sleep apnea and incident coronary heart disease and heart failure: the sleep heart health study. Circulation 2010; 122(4):352-360. PMC3117288.
            %p Redline S, Yenokyan G, Gottlieb DJ, Shahar E, O'Connor GT, Resnick HE, Diener-West M, Sanders MH, Wolfe PA, Geraghty EM, Ali T, Lebowitz M, Punjabi NM. Obstructive sleep apnea-hypopnea and incident stroke: the sleep heart health study. Am J Respir Crit Care Med. 2010; 182(2):269-277. PMC2913239.
            %p Yaffe K, Laffan AM, Harrison SL, Redline S, Spira A, Ensrud KE, Ancoli-Israel S, Stone, KL. Sleep disordered breathing, hypoxia, and risk of mild cognitive impairment and dementia in older women. JAMA. 2011; 306:613-619. PMC3600944.
            %p Koo BK, Blackwell T, Ancoli-Israel S, Stone KL, Stefanick ML, Redline S; Osteoporotic Fracture in Men (MrOS) Study Group. Association of incident cardiovascular disease with periodic limb movements during sleep in older men: outcomes of sleep disorders in older men (MrOS) study. Circulation 2011; 124(11):1223-1231. PMC3265562.
            %p Redline S, Amin R, Beebe D, Chervin RD, Garetz SL, Giordani B, Marcus CL, Moore RH,  Rosen CL,  Arens R, Gozal D, Katz ES, Mitchell R, Muzumdar H, Taylor HG, Thomas N,  Ellenberg S. The Childhood Adenotonsillectomy Trial (CHAT): rationale, design and challenges of a randomized controlled trial evaluating a standard surgical procedure in a pediatric population. Sleep. 2011; 34(11):1509-1517. PMC3198206.
            %p Sahoo SS, Ogbuji C, Luo L, Dong X, Cui L, Redline S, Zhang GQ. MiDas: automatic extraction of a common domain of discourse in sleep medicine for multi-center data integration. AMIA Annu Symp Proc. 2011; 1196-1205. PMC3243207.
            %p Blackwell T, Yaffe K, Ancoli-Israel S, Redline S, Ensrud KE, Stefanick ML, Laffan A, Stone KL; for the Osteoporotic Fractures in Men Study Group. Associations between sleep architecture and sleep-disordered breathing and cognition in older community-dwelling men: the Osteoporotic Fractures in Men Sleep Study. J Am Geriatr Soc 2011; 59(12): 2217-2225. PMC3245643.
            %p Rosen CL, Auckley D, Benca R, Foldvary-Schaefer N, Iber C, Kapur V, Rueschmann M, Zee P, Redline S. A multisite randomized trial of portable sleep studies and positive airway pressre autotitration versus laboratory-based polysomnography for the diagnosis and treatment of obstructive sleep apnea: the HomePAP study. Sleep. 2012; 35(6):757-767. PMC3353048.
            %p Facco FL, Parker CB, Reddy UM, Silver RM, Louis JM, Basner RC, Chung JH, Schubert FP, Pien GW, Redline S, Mobley DR, Koch MA, Simhan HN, Nhan-Chang CL, Parry S, Grobman WA, Haas DM, Wing DA, Mercer BM, Saade GR, Zee PC. NuMoM2b sleep-disordered breathing study: objectives and methods. Am J Obstet Gynecol. 2015; 212(4):542.e1-127. PMC4410772.
            %p Chami HA, Gottlieb DJ, Redline S, Punjabi NM. Association between glucose metabolism and sleep-disordered breathing during REM sleep. Am J Respir Crit Care Med. 2015; 192(9):1118-1126. PMC4642200.
            %p Ho V, Crainiceanu CM, Punjabi NM, Redline S, Gottlieb DJ. Calibration model for apnea-hypopnea indices: impact of alternative criteria for hypopneas. Sleep. 2015; 38(12):1887-1892. PMC4667391.
            %p Javaheri S, Blackwell T, Ancoli-Israel S, Ensrud KE, Stone KL, Redline S; Osteoporotic Fractures in Men Study (MrOS) Research Group. Sleep-disordered breathing and incident heart failure in older men. Am J Respir Crit Care Med. 2016; 193(5):561-568. PMC4824922.
            %p Dean DA 2nd, Goldberger AL, Mueller R, Kim M, Rueschman M, Mobley D, Sahoo SS, Jayapandian CP, Cui L, Morrical MG, Surovec S, Zhang GQ, Redline S. Scaling up scientific discovery in sleep medicine: the national sleep research resource. Sleep. 2016; 39(5):1151-1164. PMC4835314.
            %p Zhao YY, Blackwell T, Ensrud KE, Stone KL, Omachi TA, Redline S; Osteoporotic Fracures in Men (MrOS) Study Group. Sleep apnea and obstructive airway disease in older men: outcomes of sleep disorders in older men study. Sleep. 2016; 39(7):1343-1351. PMC4909616.
            %p Zhao YY, Weng J, Mobley DR, Wang R, Kwon Y, Zee PC, Lutsey PL, Redline S. Effect of manual editing of total recording time: implications for home sleep apnea testing. J Clin Sleep Med. 2017; 13(1):121-126. PMC5181603.
            %p Javaheri S, Sharma RK, Bluemke DA, Redline S. Association between central sleep apnea and left ventricular structure: the multi-ethnic study of atherosclerosis. J Sleep Res. 2017;  PMID: 28220556.
            %p Facco FL, Parker CB, Reddy UM, Silver RM, Koch MA, Louis JM, Basner RC, Chung JH, Nhan-Chang CL, Pien GW, Redline S, Grobman WA, Wing DA, Simhan HN, Haas DM, Mercer BM, Parry S, Mobley D, Hunter S, Saade GR, Schubert FP, Zee PC. Association between sleep-disordered breathing and hypertensive disorders of pregnancy and gestational diabetes mellitus. Obstet Gynecol. 2017; 129(1):31-41. PMID: 27926645.

          .backdrop-regular
            %p
              %strong
                Actigraphy
            %p Weiss AR, Johnson NL, Berger N, Redline R. Validity of activity-based devices to estimate sleep. J Clin Sleep Med. 2010; 6(4):336-342. PMC2919663.
            %p Johnson NJ, Kirchner HL, Storfer-Isser A, Cartar L, Ancoli-Israel S, Emancipator JL, Kibler AM, Redline S. Sleep estimation using wrist actigraphy in adolescents with and without sleep disordered breathing: a comparison of three data modes. Sleep. 2007; 30(7):899-905. PMC1978368.
            %p Weiss A, Xu F, Storfer-Isser A, Thomas A, Landis-Ievers CE, Redline S. The association of sleep duration with adolescents' fat and carbohydrate consumption. Sleep. 2010; 33(9):1201-1209. PMC2938861.
            %p Javaheri S, Storfer-Isser A, Rosen CL, Redline S. Association of short and long sleep durations with insulin sensitivity in adolescents. J Pediatr. 2011; 158(4):617-623. PMC3076647.
            %p Fung MM, Peters K, Ancoli-Israel S, Redline S, Stone KL, Barrett-Connor E; Osteporotic Fractures in Men (MrOS) Research Group. Total sleep time and other sleep characteristics measured by actigraphy do not predict incident hypertension in a cohort of community-dwelling older men. J Clin Sleep Med. 2013; 9(6):585-591. PMC3659379.
            %p Bakker JP, Weng J, Wang R, Redline S, Punjabi NM, Patel SR. Associations between obstructive sleep apnea, sleep duration, and abnormal fasting glucose. The multi-ethnic study of atherosclerosis. Am J Respir Crit Care Med. 2015; 192(6):745-753. PMC4595677.
            %p Nagayoshi M, Lutsey PL, Benkesser D, Wassel CL, Folsom AR, Shahar E, Iso H, Allison MA, Criqui MH, Redline S. Association of sleep apnea and sleep duration with peripheral artery disease: the multi-ethnic study of atherosclerosis (MESA). Atherosclerosis. 2016; 251:467-475. PMC4983210.
            %p Ogilvie RP, Redline S, Bertoni AG, Chen X, Ouyang P, Szklo M, Lutsey PL.  Actigraphy measured sleep indices and adiposity: the multi-ethnic study of atherosclerosis (MESA). Sleep. 2016; 39(9):1701-1708. PMC4989259.
            %p Castro-Diehl C, Diez Roux AV, Redline S, Seeman T, McKinley P, Sloan R, Shea S. Sleep duration and quality in relation to autonomic nervous system measures: the multi-ethnic study of atherosclerosis (MESA). Sleep. 2016; 39(11):1927-1940. PMC5070747.
            %p Cespedes EM, Hu FB, Redline S, Rosner B, Alcantara C, Cai J, Hall MH, Loredo JS, Mossavar-Rahmani Y, Ramos AR, Reid KJ, Shah NA, Sotres-Alvarez D, Zee PC, Wang R, Patel SR. Comparison of self-reported sleep duration with actigraphy: results from the Hispanic Community Health Study/Study of Latinos Sueño Ancillary Study. Am J Epidemiol. 2016; 183(6):561-573. PMC4782764.

          .backdrop-regular
            %p
              %strong
                CPAP adherence monitoring
            %p Billings ME, Auckley D, Benca R, Foldvary-Schaefer N, Iber C, Redline S, Rosen CL, Zee P, Kapur VK. Race and residential socioeconomics as predictors of CPAP adherence. Sleep. 2011; 34(12):1653-1658. PMC3208842.
            %p Billings ME, Rosen CL, Wang R, Auckley D, Benca R, Foldvary-Schaefer N, Iber C, Zee P, Redline S, Kapur VK. Is the relationship between race and continuous positive airway pressure adherence mediated by sleep duration? Sleep. 2013; 36(2):221-227. PMC3543052.
            %p Bakker JP, Wang R, Weng J, Aloia MS, Toth C, Morrical MG, Gleason KJ, Rueschman M, Dorsey C, Patel SR, Ware JH, Mittleman MA, Redline S. Motivational enhancement for increasing adherence to CPAP: a randomized controlled trial. Chest. 2016; 150(2):337-345. PMC4980541.

          .backdrop-regular
            %p
              = link_to personnel_path do
                Our personnel
                = icon("fas", "caret-right")

app/views/layouts/_footer.html.haml
.footer-container
  .container
    .footer
      .nowrap.row
        .col
          &copy;
          = Time.zone.today.year
          .d-inline.d-md-none= link_to "SRC", about_path
          .d-none.d-md-inline
            Sleep Reading Center
            &nbsp;
            = link_to "About", about_path

        .col.text-center.d-none.d-sm-block
          - if false
            %small.px-2= link_to "Terms", terms_and_conditions_path
          %small.px-2= link_to "Privacy", privacy_policy_path

        .col.text-right
          %div{ style: "margin-top: -14px;" }
            = link_to "Questions?", contact_path
            &nbsp;
            = link_to image_tag("logos/bwh-logo.png", size: "48x56"), "http://www.brighamandwomens.org/"

app/views/menu/_left_menu.html.haml
%nav.nav.flex-column.left-menu
  = render "menu/item_link", title: "SRC", path: root_path
  = render "menu/item_link", title: "About", path: about_path
  = render "menu/item_link", title: "Services", path: services_path
  = render "menu/item_link", title: "Facility", path: facility_path
  = render "menu/item_link", title: "Research", path: research_path
  = render "menu/item_link", title: "Personnel", path: personnel_path
  = render "menu/item_link", title: "Contact", path: contact_path